name: CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [10.x, 11.x, 12.x, 13.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run lint
      - run: npm test
        env:
          CI: true
          DATABASE_SSL_ENABLED: true
          DATABASE_CONNECTION: ${{ secrets.DATABASE_CONNECTION }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
