name: CI

on: [ push, pull_request ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [16.x, 18.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: node --version
      - run: npm --version
      - run: npm install
      - run: npm run lint
      - run: npm run test:types
      - run: npm test
      - run: npm run transpile:cjs
      - run: npm run test:cjs:types
      - run: npm test:cjs
        env:
          CI: true
          DATABASE_SSL_ENABLED: ${{ secrets.DATABASE_SSL_ENABLED }}
          DATABASE_CONNECTION: ${{ secrets.DATABASE_CONNECTION }}
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
